# Trims the LocalNet to fit a 7.8 GB Docker VM next to other containers.
services:
  postgres:
    mem_limit: 1g
  canton:
    mem_limit: 3g
    environment:
      _JAVA_OPTIONS: '-XX:-UseCompressedOops -Xms512m -Xmx2g'
  splice:
    mem_limit: 2560m
    environment:
      _JAVA_OPTIONS: '-XX:-UseCompressedOops -Xms512m -Xmx1800m'
